/*PLEASE DO NOT EDIT THIS CODE*/
/*This code was generated using the UMPLE 1.37.0.8623.1cd95c4b0 modeling language!*/

package project_db.v01;
import java.util.*;

/**
 * -----------------------------------------------------------------------------
 * Canonical base — every multi-source entity inherits from this
 * -----------------------------------------------------------------------------
 */
// line 98 "../../model-v0.1.ump"
public abstract class CanonicalEntity
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //CanonicalEntity Attributes
  private UUID canonicalId;
  private DateTime createdAt;
  private DateTime updatedAt;
  private String notes;

  //CanonicalEntity Associations
  private List<ExternalId> externalIds;

  //Helper Variables
  private int cachedHashCode;

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public CanonicalEntity(UUID aCanonicalId, DateTime aCreatedAt, DateTime aUpdatedAt)
  {
    cachedHashCode = -1;
    canonicalId = aCanonicalId;
    createdAt = aCreatedAt;
    updatedAt = aUpdatedAt;
    notes = null;
    externalIds = new ArrayList<ExternalId>();
  }

  //------------------------
  // INTERFACE
  //------------------------

  public boolean setUpdatedAt(DateTime aUpdatedAt)
  {
    boolean wasSet = false;
    updatedAt = aUpdatedAt;
    wasSet = true;
    return wasSet;
  }

  public boolean setNotes(String aNotes)
  {
    boolean wasSet = false;
    notes = aNotes;
    wasSet = true;
    return wasSet;
  }

  /**
   * internal UUID, generated by DB
   */
  public UUID getCanonicalId()
  {
    return canonicalId;
  }

  /**
   * never changes after construction
   */
  public DateTime getCreatedAt()
  {
    return createdAt;
  }

  public DateTime getUpdatedAt()
  {
    return updatedAt;
  }

  public String getNotes()
  {
    return notes;
  }
  /* Code from template association_GetMany */
  public ExternalId getExternalId(int index)
  {
    ExternalId aExternalId = externalIds.get(index);
    return aExternalId;
  }

  public List<ExternalId> getExternalIds()
  {
    List<ExternalId> newExternalIds = Collections.unmodifiableList(externalIds);
    return newExternalIds;
  }

  public int numberOfExternalIds()
  {
    int number = externalIds.size();
    return number;
  }

  public boolean hasExternalIds()
  {
    boolean has = externalIds.size() > 0;
    return has;
  }

  public int indexOfExternalId(ExternalId aExternalId)
  {
    int index = externalIds.indexOf(aExternalId);
    return index;
  }
  /* Code from template association_MinimumNumberOfMethod */
  public static int minimumNumberOfExternalIds()
  {
    return 0;
  }
  /* Code from template association_AddManyToOne */
  public ExternalId addExternalId(SourceSystem aSource, String aExternalKey, String aEntityType, DateTime aLastSyncedAt)
  {
    return new ExternalId(aSource, aExternalKey, aEntityType, aLastSyncedAt, this);
  }

  public boolean addExternalId(ExternalId aExternalId)
  {
    boolean wasAdded = false;
    if (externalIds.contains(aExternalId)) { return false; }
    CanonicalEntity existingCanonicalEntity = aExternalId.getCanonicalEntity();
    boolean isNewCanonicalEntity = existingCanonicalEntity != null && !this.equals(existingCanonicalEntity);
    if (isNewCanonicalEntity)
    {
      aExternalId.setCanonicalEntity(this);
    }
    else
    {
      externalIds.add(aExternalId);
    }
    wasAdded = true;
    return wasAdded;
  }

  public boolean removeExternalId(ExternalId aExternalId)
  {
    boolean wasRemoved = false;
    //Unable to remove aExternalId, as it must always have a canonicalEntity
    if (!this.equals(aExternalId.getCanonicalEntity()))
    {
      externalIds.remove(aExternalId);
      wasRemoved = true;
    }
    return wasRemoved;
  }
  /* Code from template association_AddIndexControlFunctions */
  public boolean addExternalIdAt(ExternalId aExternalId, int index)
  {  
    boolean wasAdded = false;
    if(addExternalId(aExternalId))
    {
      if(index < 0 ) { index = 0; }
      if(index > numberOfExternalIds()) { index = numberOfExternalIds() - 1; }
      externalIds.remove(aExternalId);
      externalIds.add(index, aExternalId);
      wasAdded = true;
    }
    return wasAdded;
  }

  public boolean addOrMoveExternalIdAt(ExternalId aExternalId, int index)
  {
    boolean wasAdded = false;
    if(externalIds.contains(aExternalId))
    {
      if(index < 0 ) { index = 0; }
      if(index > numberOfExternalIds()) { index = numberOfExternalIds() - 1; }
      externalIds.remove(aExternalId);
      externalIds.add(index, aExternalId);
      wasAdded = true;
    } 
    else 
    {
      wasAdded = addExternalIdAt(aExternalId, index);
    }
    return wasAdded;
  }

  public boolean equals(Object obj)
  {
    if (obj == null) { return false; }
    if (!getClass().equals(obj.getClass())) { return false; }

    CanonicalEntity compareTo = (CanonicalEntity)obj;
  
    if (getCanonicalId() == null && compareTo.getCanonicalId() != null)
    {
      return false;
    }
    else if (getCanonicalId() != null && !getCanonicalId().equals(compareTo.getCanonicalId()))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    if (cachedHashCode != -1)
    {
      return cachedHashCode;
    }
    cachedHashCode = 17;
    if (getCanonicalId() != null)
    {
      cachedHashCode = cachedHashCode * 23 + getCanonicalId().hashCode();
    }
    else
    {
      cachedHashCode = cachedHashCode * 23;
    }

    
    return cachedHashCode;
  }

  public void delete()
  {
    while (externalIds.size() > 0)
    {
      ExternalId aExternalId = externalIds.get(externalIds.size() - 1);
      aExternalId.delete();
      externalIds.remove(aExternalId);
    }
    
  }


  public String toString()
  {
    return super.toString() + "["+
            "notes" + ":" + getNotes()+ "]" + System.getProperties().getProperty("line.separator") +
            "  " + "canonicalId" + "=" + (getCanonicalId() != null ? !getCanonicalId().equals(this)  ? getCanonicalId().toString().replaceAll("  ","    ") : "this" : "null") + System.getProperties().getProperty("line.separator") +
            "  " + "createdAt" + "=" + (getCreatedAt() != null ? !getCreatedAt().equals(this)  ? getCreatedAt().toString().replaceAll("  ","    ") : "this" : "null") + System.getProperties().getProperty("line.separator") +
            "  " + "updatedAt" + "=" + (getUpdatedAt() != null ? !getUpdatedAt().equals(this)  ? getUpdatedAt().toString().replaceAll("  ","    ") : "this" : "null");
  }
}